### ISSUE TITLE
ImportError: No module named pip_downloader.cli

### ISSUE THREAD

**Issue by yukselao** [AbdealiJK/pip-downloader#14]
Hello,

How can we solve it?

[root@li1501-192 ~]# python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

[root@li1501-192 ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 

[root@li1501-192 ~]# pip-downloader list flusk
Traceback (most recent call last):
  File "/usr/bin/pip-downloader", line 11, in <module>
    load_entry_point('pip-downloader==0.2', 'console_scripts', 'pip-downloader')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named pip_downloader.cli

**Comment by feature-engineer** [comment]
I get the a similar thing on python 3.6.9, Ubuntu 18.04:

`Traceback (most recent call last):
  File "/home/user/projects/envs/gen_env/bin/pip-downloader", line 5, in <module>
    from pip_downloader.cli import main
ModuleNotFoundError: No module named 'pip_downloader.cli'
`

**Comment by it-is-wednesday** [comment]
My `site-packages/pip-downloader` directory seems empty - only `__init__.py` is there. I'm not a pip expert, so I'll just kindly suggest using [pip-download](https://pypi.org/project/pip-download/) instead. They seem to accomplish a similar goal.

**Comment by elenakrittik** [comment]
The same with Python 3.10
```sh
pip-downloader download disnake                           ✔  6s  
Traceback (most recent call last):
  File "/usr/bin/pip-downloader", line 5, in <module>
    from pip_downloader.cli import main
ModuleNotFoundError: No module named 'pip_downloader.cli'
```
