### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by nbaker101** [AbdealiJK/pip-downloader#5]
After doing a pip install of this package I'm getting the following error.

C:\Users\User>pip-downloader --help
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\Scripts\pip-downloader.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'pip_downloader.cli'

pip --version
pip 19.2.1 from c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

C:\Users\user>python --version
Python 3.7.1

**Comment by bmayfi3ld** [comment]
I can confirm this as well. It looks like none of the python files get downloaded when you install it with pip.

**Comment by kokare-darshan** [comment]
I am still facing this issue, request to reopen
